import nbformat
from pathlib import Path
p=Path('notebooks/week5_deep_learning.ipynb')
nb=nbformat.v4.new_notebook()
nb.metadata={'kernelspec':{'display_name':'Python 3','language':'python','name':'python3'},'language_info':{'name':'python','version':'3.13'}}
nb.cells=[
 nbformat.v4.new_markdown_cell('# Week 5 — Deep Learning Model Development and Evaluation\n**Student:** Vikhyath Bharadwaj K S  \n**Project:** Handwritten digit classification with a convolutional neural network  \n\nThis notebook trains a compact PyTorch CNN on scikit-learn’s bundled copy of the UCI Optical Recognition of Handwritten Digits dataset. The bundled source makes the analysis reproducible without a network download. Fashion-MNIST was considered but could not be fetched in the restricted runtime.'),
 nbformat.v4.new_markdown_cell('## 1. Problem and dataset\nClassify each 8×8 grayscale image (pixel intensities 0–16) as one of ten handwritten digits. This is supervised, single-label, multiclass image classification. The dataset contains 1,797 examples (179 per digit, with a few class-count rounding differences). Images are normalized to [0,1]. We create stratified train, validation, and test subsets (70/15/15; seed 42).'),
 nbformat.v4.new_code_cell("from sklearn.datasets import load_digits\nimport numpy as np\ndata=load_digits()\nprint('Images:', data.images.shape, 'Labels:', data.target.shape)\nprint('Pixel range:', data.images.min(), 'to', data.images.max())\nprint('Class counts:', np.bincount(data.target))"),
 nbformat.v4.new_code_cell("import matplotlib.pyplot as plt\nfig,ax=plt.subplots(2,5,figsize=(9,4))\nfor digit,a in enumerate(ax.flat):\n    i=np.flatnonzero(data.target==digit)[0]; a.imshow(data.images[i],cmap='gray'); a.set_title(f'Label {digit}'); a.axis('off')\nplt.tight_layout()"),
 nbformat.v4.new_markdown_cell('## 2. Architecture and training setup\nTwo convolution blocks use 3×3 convolutions (16 then 32 filters), ReLU, and 2×2 max pooling. The 32×2×2 feature map feeds a 64-unit ReLU layer, 20% dropout, and ten logits. Cross-entropy loss and Adam (learning rate 0.001) are used with batch size 64 for 30 epochs. Validation loss selects the saved best checkpoint. No augmentation is used because the dataset is small and its orientation/shape transformations may alter the digit label.'),
 nbformat.v4.new_code_cell("from pathlib import Path\nimport sys\nROOT=Path.cwd()\nif not (ROOT/'src'/'week5'/'train.py').exists(): ROOT=ROOT.parent\nsys.path.insert(0,str(ROOT))\nfrom src.week5.train import DigitsCNN, main\nmodel=DigitsCNN()\nprint(model)"),
 nbformat.v4.new_markdown_cell('## 3. Train and evaluate\nThe cell below performs the stratified split, trains the CNN, selects the checkpoint by validation loss, evaluates once on the held-out test partition, and writes metrics, weights, and visualizations into the repository. The test data are not used for model selection.'),
 nbformat.v4.new_code_cell("metrics=main(epochs=30,batch_size=64)\nprint(f\"Test accuracy: {metrics['test_accuracy']:.4f}\")\nprint(f\"Test macro F1: {metrics['test_macro_f1']:.4f}\")\nprint(f\"Test weighted F1: {metrics['test_weighted_f1']:.4f}\")"),
 nbformat.v4.new_markdown_cell('## 4. Learning curves and error analysis'),
 nbformat.v4.new_code_cell("from IPython.display import display, Image\nfor name in ['training_curves.png','confusion_matrix.png','architecture.png','misclassified_examples.png']:\n    path=ROOT/'visualizations'/'week5'/name\n    print(name)\n    display(Image(filename=str(path)))"),
 nbformat.v4.new_code_cell("from sklearn.metrics import classification_report\nprint(classification_report(\n    np.array(data.target)[np.array_split(np.arange(len(data.target)), 1)[0]][:0] if False else [], []))"),
 nbformat.v4.new_markdown_cell('## 5. Interpretation and limitations\nDigits is a compact benchmark (1,797 observations and 8×8 resolution), not a deployment dataset. Results can vary by framework/hardware despite fixed seeds, and a single split has sampling uncertainty. Handwritten style and the low resolution constrain generalization. Compare per-class precision/recall and inspect the saved confusion matrix before drawing conclusions. Model and run artifacts are intentionally excluded from Git; regenerate them with `python src/week5/train.py`.')]
# Replace unused placeholder with useful per-class metrics display sourced from run json.
nb.cells[9]=nbformat.v4.new_code_cell("import json\nrun=json.loads((ROOT/'models'/'week5'/'metrics.json').read_text(encoding='utf-8'))\nfor label in run['labels']:\n    row=run['classification_report'][label]\n    print(f\"{label}: precision={row['precision']:.3f}, recall={row['recall']:.3f}, F1={row['f1-score']:.3f}, n={int(row['support'])}\")")
nbformat.write(nb,p)
