from pathlib import Path
import json
from docx import Document
from docx.shared import Inches,Pt,RGBColor
from docx.enum.text import WD_ALIGN_PARAGRAPH
from docx.enum.table import WD_TABLE_ALIGNMENT, WD_CELL_VERTICAL_ALIGNMENT
from docx.oxml import OxmlElement
from docx.oxml.ns import qn
ROOT=Path(__file__).resolve().parents[2]
m=json.loads((ROOT/'models/week5/metrics.json').read_text(encoding='utf-8'))
doc=Document(); sec=doc.sections[0]; sec.top_margin=Inches(.7);sec.bottom_margin=Inches(.65);sec.left_margin=Inches(.8);sec.right_margin=Inches(.8)
styles=doc.styles;styles['Normal'].font.name='Aptos';styles['Normal'].font.size=Pt(10);styles['Normal'].paragraph_format.space_after=Pt(5)
for name,size,color in [('Title',27,'163A5F'),('Heading 1',17,'163A5F'),('Heading 2',13,'276678')]:
 s=styles[name];s.font.name='Aptos Display';s.font.size=Pt(size);s.font.bold=True;s.font.color.rgb=RGBColor.from_string(color)
footer=sec.footer.paragraphs[0];footer.alignment=WD_ALIGN_PARAGRAPH.CENTER
footer.add_run('Yuva Internship · Week 5  |  ')
fld=OxmlElement('w:fldSimple');fld.set(qn('w:instr'),'PAGE');footer._p.append(fld)
def para(text='',style=None,boldlead=None):
 p=doc.add_paragraph(style=style)
 if boldlead and text.startswith(boldlead):p.add_run(boldlead).bold=True;p.add_run(text[len(boldlead):])
 else:p.add_run(text)
 return p
def heading(text,level=1):doc.add_heading(text,level)
def bullet(text):doc.add_paragraph(text,style='List Bullet')
def table(headers,rows,widths=None):
 t=doc.add_table(rows=1,cols=len(headers));t.style='Light Shading Accent 1';t.alignment=WD_TABLE_ALIGNMENT.CENTER
 for c,txt in zip(t.rows[0].cells,headers): c.text=str(txt);c.vertical_alignment=WD_CELL_VERTICAL_ALIGNMENT.CENTER
 for row in rows:
  cells=t.add_row().cells
  for c,txt in zip(cells,row):c.text=str(txt);c.vertical_alignment=WD_CELL_VERTICAL_ALIGNMENT.CENTER
 return t
def figure(name,caption,width=6.2):
 path=ROOT/'visualizations/week5'/name
 if path.exists():
  doc.add_picture(str(path),width=Inches(width));p=doc.add_paragraph(caption);p.alignment=WD_ALIGN_PARAGRAPH.CENTER;p.runs[0].italic=True
# Cover
p=doc.add_paragraph();p.alignment=WD_ALIGN_PARAGRAPH.CENTER;p.paragraph_format.space_before=Pt(90);r=p.add_run('YUVA INTERNSHIP');r.bold=True;r.font.size=Pt(17);r.font.color.rgb=RGBColor(39,102,120)
p=doc.add_paragraph();p.alignment=WD_ALIGN_PARAGRAPH.CENTER;p.paragraph_format.space_before=Pt(24);r=p.add_run('WEEK 5');r.bold=True;r.font.size=Pt(34);r.font.color.rgb=RGBColor(22,58,95)
p=doc.add_paragraph();p.alignment=WD_ALIGN_PARAGRAPH.CENTER;r=p.add_run('Deep Learning Model\nDevelopment and Evaluation');r.bold=True;r.font.size=Pt(22)
p=doc.add_paragraph();p.alignment=WD_ALIGN_PARAGRAPH.CENTER;p.paragraph_format.space_before=Pt(30)
p.add_run('Project: Deep Learning Model Development and Evaluation Using Python\n').bold=True;p.add_run('Student: Vikhyath Bharadwaj K S\nDataset: UCI Optical Recognition of Handwritten Digits\nSubmission date: 3 October 2026')
doc.add_page_break()
heading('Contents',1);para('This report is organized into the sections listed below. In Microsoft Word, use References → Table of Contents to insert an automatically paginated TOC if desired.')
for x in ['Abstract','1. Introduction','2. Dataset Description','3. Problem Statement and Methodology','4. Data Exploration and Preprocessing','5. Neural Network Architecture','6. Model Implementation','7. Training and Optimization','8. Evaluation and Results','9. Error Analysis','10. Challenges and Solutions','11. Critical Analysis and Future Scope','12. Conclusion','References','Appendix']:bullet(x)
heading('Abstract');para(f"This project develops a compact convolutional neural network (CNN) to classify 8×8 grayscale images of handwritten digits into ten classes. The offline-bundled UCI Optical Recognition of Handwritten Digits dataset contains 1,797 images. A stratified 70/15/15 split was used for training, validation, and final testing. The PyTorch model uses two convolution and max-pooling blocks followed by a 64-unit dense layer, dropout, and ten output logits. Adam optimization with cross-entropy trained for 30 epochs, with the lowest validation-loss checkpoint retained. On the 270-image held-out test split the model achieved {m['test_accuracy']:.2%} accuracy, {m['test_macro_f1']:.3f} macro-F1, and {m['test_weighted_f1']:.3f} weighted-F1. The small dataset and low image resolution limit generalization claims; results are a reproducible educational baseline, not a production OCR evaluation.")
heading('1. Introduction');para('Deep learning uses layered parameterized functions to learn representations from examples. In a neural network, learned weights combine inputs, nonlinear activation functions add expressive capacity, and gradient-based optimization adjusts parameters to reduce a loss. A convolutional neural network is suited to image inputs because local filters can detect spatial patterns such as strokes and edges while pooling reduces spatial dimensions.')
para('The Week 5 objective is to implement an end-to-end neural workflow, monitor validation behavior, evaluate on a held-out test set, and analyze class-level errors. Fashion-MNIST, MNIST, CIFAR-10, and tabular options were considered. Fashion-MNIST was initially selected, but outbound data downloads were unavailable in the runtime. The chosen digits dataset is bundled with scikit-learn and can be loaded without network access, making complete execution and reproducibility practical. It is a small benchmark and less challenging than MNIST/Fashion-MNIST.')
heading('2. Dataset Description');para('The data come from the UCI Optical Recognition of Handwritten Digits collection. The scikit-learn `load_digits` copy provides 1,797 8×8 grayscale images, 64 pixel features per image, and ten target labels (0–9). Pixel intensities are integers from 0 to 16. The source describes normalized bitmaps derived from handwritten forms; the bundled version is compact and readily accessible. The UCI record identifies CC BY 4.0 licensing; attribution should be preserved.')
table(['Property','Description'],[['Observations','1,797 images'],['Image dimensions','8×8 grayscale'],['Features','64 pixel intensities (0–16)'],['Target','Digit class 0 through 9'],['Task','Supervised multiclass classification'],['Missing / duplicate checks','Bundled numeric arrays; no missing pixels; duplicate image review is not used as a removal criterion'],['Limitations','Small sample, coarse resolution, limited handwriting variation']])
heading('3. Problem Statement and Methodology');para('Given a 64-value image tensor, predict exactly one digit label from ten classes. The output is a ten-dimensional vector of unnormalized class scores; the largest score selects the predicted class. The workflow is: load bundled examples → inspect and normalize → stratified split → train CNN and monitor validation → restore best validation checkpoint → evaluate once on the untouched test partition → save metrics, weights, and figures.')
heading('4. Data Exploration and Preprocessing');para('The images are reshaped from (N, 8, 8) to (N, 1, 8, 8) to add the grayscale channel axis. Pixel intensities are converted to float32 and divided by 16 so values lie in [0,1]. Labels are integer encoded 0–9, as required by PyTorch cross-entropy. No imputing or categorical encoding is needed. Stratification retains similar class proportions in the 70% train, 15% validation, and 15% test partitions. The random seed is 42. The test set is reserved until the final evaluation. Since this built-in dataset has no fitted scaling transform, normalization is deterministic and cannot leak test statistics.')
para(f"The actual split contained {m['train_n']} training, {m['validation_n']} validation, and {m['test_n']} test images.")
heading('5. Neural Network Architecture');para('The CNN uses a 3×3 convolution with 16 filters and same padding, ReLU, and 2×2 max-pooling, followed by a second 3×3 convolution with 32 filters, ReLU, and pooling. The representation changes from 1×8×8 to 16×4×4, then 32×2×2; flattening yields 128 values. A 64-neuron ReLU layer and dropout probability 0.20 precede ten logits. Cross-entropy is numerically stable for raw logits.')
figure('architecture.png','Figure 1. CNN layer sequence and tensor dimensions.',6.4)
table(['Setting','Value','Rationale'],[['Loss','CrossEntropyLoss','Multiclass logits and integer labels'],['Optimizer','Adam','Adaptive first-order optimizer'],['Learning rate','0.001','Common stable baseline'],['Batch size','64','Balances gradient stability and small dataset'],['Epochs','30','Fixed reproducible training budget'],['Regularization','Dropout 0.20','Reduces dense-layer co-adaptation'],['Checkpoint','Minimum validation loss','Selects without using test results']])
heading('6. Model Implementation');para('Implementation is modular in `src/week5/train.py`. `DigitsCNN` defines the layer graph, while `main` loads and splits data, builds data loaders, trains the model, restores the best checkpoint, calculates metrics, and exports artifacts. Seeds are set for NumPy and PyTorch. Model weights and metrics are saved locally under `models/week5/`; generated figures go to `visualizations/week5/`. The notebook documents the same workflow and invokes this implementation.')
para('Core model definition:')
code=doc.add_paragraph();run=code.add_run('Conv2d(1,16,3,padding=1) → ReLU → MaxPool2d(2)\nConv2d(16,32,3,padding=1) → ReLU → MaxPool2d(2)\nFlatten → Linear(128,64) → ReLU → Dropout(0.20) → Linear(64,10)');run.font.name='Consolas';run.font.size=Pt(9)
heading('7. Training and Optimization');para(f"Training ran on CPU for {m['duration_seconds']:.2f} seconds in this environment. Training loss fell from {m['history']['loss'][0]:.3f} to {m['history']['loss'][-1]:.3f}; validation accuracy reached {max(m['history']['val_accuracy']):.1%}. The best validation-loss checkpoint was retained. Training/validation divergence late in training is a possible overfitting signal on this small sample, although the validation scores remained high. No hyperparameter search or augmentation experiment was conducted; the selected setup is a baseline.")
figure('training_curves.png','Figure 2. Training and validation loss/accuracy across epochs.')
heading('8. Evaluation and Results');para(f"On the held-out test partition (n={m['test_n']}), accuracy was {m['test_accuracy']:.4f}, macro-F1 was {m['test_macro_f1']:.4f}, and weighted-F1 was {m['test_weighted_f1']:.4f}. Macro-F1 weights each digit equally; weighted-F1 weights by test support. These aggregate metrics indicate strong classification on this split but do not establish performance on different writers or acquisition conditions.")
table(['Metric','Test result'],[['Accuracy',f"{m['test_accuracy']:.4f}"],['Macro precision',f"{m['classification_report']['macro avg']['precision']:.4f}"],['Macro recall',f"{m['classification_report']['macro avg']['recall']:.4f}"],['Macro-F1',f"{m['test_macro_f1']:.4f}"],['Weighted-F1',f"{m['test_weighted_f1']:.4f}"]])
rows=[[k,f"{v['precision']:.3f}",f"{v['recall']:.3f}",f"{v['f1-score']:.3f}",str(int(v['support']))] for k,v in m['classification_report'].items() if k.isdigit()]
table(['Digit','Precision','Recall','F1','Support'],rows)
figure('confusion_matrix.png','Figure 3. Confusion matrix on the held-out test partition.')
figure('misclassified_examples.png','Figure 4. Incorrect test predictions, showing true and predicted labels.')
heading('9. Error Analysis');errs=m['incorrect_examples'];para(f"There were {round((1-m['test_accuracy'])*m['test_n'])} incorrect test predictions. The confusion matrix and error examples should be inspected for visually similar handwritten forms; the report includes actual misclassified examples generated from this run. At only 8×8 pixels, ambiguous strokes and reduced detail can make classes visually indistinguishable. Per-class precision and recall are included above to reveal any classes with weaker performance.")
heading('10. Challenges and Solutions');bullet('Fashion-MNIST download failed because outbound DNS/network access was unavailable; switched to the bundled scikit-learn digits data to preserve a fully executable image task.');bullet('The dataset is small and low resolution; kept the CNN compact and used a held-out validation set to choose the checkpoint.');bullet('Training variability is controlled with fixed NumPy/PyTorch seeds; exact determinism across hardware/runtime builds is not guaranteed.')
heading('11. Critical Analysis and Future Scope');para('The CNN learns spatial stroke features and performs well on the chosen random split, but the benchmark contains fewer examples than modern OCR datasets. A random split may place similar writing styles across partitions, so the result can overstate writer-independent generalization. Future work should use a larger writer-diverse dataset (MNIST or Fashion-MNIST once available), group splits by writer where IDs exist, compare a compact MLP and CNN, run repeated seeds, inspect calibration, and test augmentation policies that preserve digit identity. Saved model weights are for reproducibility rather than deployment.')
heading('12. Conclusion');para(f"The Week 5 workflow covers data inspection, image normalization, stratified splitting, CNN design, training, checkpoint selection, evaluation, error visualization, and artifact generation. The executed model achieved {m['test_accuracy']:.2%} test accuracy with {m['test_macro_f1']:.3f} macro-F1 on the 270-example held-out set. The main practical lesson is that a reproducible modest baseline and honest dataset limitations are more informative than unsupported claims from an unverified run.")
heading('References');
for txt in ['UCI Machine Learning Repository. Optical Recognition of Handwritten Digits. https://archive.ics.uci.edu/dataset/80/optical+recognition+of+handwritten+digits (CC BY 4.0).','scikit-learn Developers. load_digits API documentation. https://scikit-learn.org/stable/modules/generated/sklearn.datasets.load_digits.html','PyTorch. torch.nn documentation. https://pytorch.org/docs/stable/nn.html','PyTorch. Optimizers documentation (Adam). https://pytorch.org/docs/stable/optim.html','Pedregosa, F. et al. (2011). Scikit-learn: Machine Learning in Python. Journal of Machine Learning Research, 12, 2825–2830.']:bullet(txt)
heading('Appendix: Validation checklist');
for item in ['Dataset dimensions and class labels inspected.','Pixel normalization and tensor dimensions checked in implementation.','Stratified train/validation/test split saved in metrics.','CNN architecture and hyperparameters documented.','Training completed for all 30 epochs; best validation-loss checkpoint evaluated.','Held-out metrics and confusion matrix generated from the executed model.','Architecture and learning curve figures generated.','Notebook execution and DOCX rendering require final environment check.','Earlier Week 1–4 deliverables remain in the repository.','Weights and source dataset are excluded from Git; regenerate using the documented command.']:bullet('☑ '+item)
doc.core_properties.title='Week 5 Deep Learning Model Development and Evaluation';doc.core_properties.author='Vikhyath Bharadwaj K S';doc.core_properties.subject='Yuva Internship Week 5';
out=ROOT/'reports'/'Week5_Deep_Learning_Report.docx';doc.save(out);print(out)
